//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace Xilium.CefGlue
{
    using System;
    using System.Collections.Generic;
    using System.Diagnostics;
    using System.Runtime.InteropServices;
    using Xilium.CefGlue.Interop;
    
    // Role: PROXY
    public sealed unsafe partial class CefComponent : IDisposable
    {
        internal static CefComponent FromNative(cef_component_t* ptr)
        {
            return new CefComponent(ptr);
        }
        
        internal static CefComponent FromNativeOrNull(cef_component_t* ptr)
        {
            if (ptr == null) return null;
            return new CefComponent(ptr);
        }
        
        private cef_component_t* _self;
        
        private CefComponent(cef_component_t* ptr)
        {
            if (ptr == null) throw new ArgumentNullException("ptr");
            _self = ptr;
        }
        
        ~CefComponent()
        {
            if (_self != null)
            {
                Release();
                _self = null;
            }
        }
        
        public void Dispose()
        {
            if (_self != null)
            {
                Release();
                _self = null;
            }
            GC.SuppressFinalize(this);
        }
        
        internal void AddRef()
        {
            cef_component_t.add_ref(_self);
        }
        
        internal bool Release()
        {
            return cef_component_t.release(_self) != 0;
        }
        
        internal bool HasOneRef
        {
            get { return cef_component_t.has_one_ref(_self) != 0; }
        }
        
        internal bool HasAtLeastOneRef
        {
            get { return cef_component_t.has_at_least_one_ref(_self) != 0; }
        }
        
        internal cef_component_t* ToNative()
        {
            AddRef();
            return _self;
        }
    }
}
